### ISSUE TITLE
Memory leaks after initializing this extension

### ISSUE THREAD

**Issue by jamesobutler** [VASST/SlicerCamera#4]
Tested with Slicer 4.10.1:
When this extension is installed, simply starting Slicer which initializes the extension and then immediately closing Slicer results in the following leaks:
```log
vtkDebugLeaks has detected LEAKS!
Class "vtkMatrix3x3" has 1 instance still around.
Class "vtkMatrix4x4" has 1 instance still around.
Class "vtkDoubleArray" has 1 instance still around.
Class "class vtkBuffer<double>" has 1 instance still around.
```

**Comment by adamrankin** [comment]
These are the members of `vtkMRMLVideoCameraNode`

I will investigate. They are set to nullptr on `~vtkMRMLVideoCameraNode() ` but perhaps there's a dangling reference to a `vtkMRMLVideoCameraNode`

**Comment by adamrankin** [comment]
Potentially in `~qMRMLVideoCameraIntrinsicsWidget` adding a set null

**Comment by adamrankin** [comment]
Nope...

**Comment by adamrankin** [comment]
Building debug :(

**Comment by jamesobutler** [comment]
Yep, those pesky leaks! Thanks for looking into it

**Comment by adamrankin** [comment]
I have no idea....

**Comment by jamesobutler** [comment]
@adamrankin If you suspect https://github.com/VASST/SlicerVideoCameras/commit/a3f6bc07242d6d10076231ae278af38dbd3c54f9 will also work on Slicer 4.10.1 and not just Slicer Nightly, can you push the commit to your "4.10" branch in this repo?
