### ISSUE TITLE
Errors when integrating the extension in 3D Slicer 5.6.1

### ISSUE THREAD

**Issue by mcqueen003** [VASST/SlicerCamera#7]
Hi,

Is the extension compatible with Slicer 5.6.1? I get the following error when trying to integrate it from the Extension Wizard:
<img width="707" alt="Error_SlicerPinholeCameras" src="https://github.com/VASST/SlicerPinholeCameras/assets/160881077/5049ab87-a104-4482-8fa0-16e7514a2ba6">

Thank you

**Comment by adamrankin** [comment]
At this time I am not maintaining the extension. Pull requests are welcome.
